INSERT INTO public."Zona" (nombre) VALUES
	 ('ZONA 1'),
	 ('ZONA 2'),
	 ('ZONA 3'),
	 ('ZONA 4'),
	 ('ZONA 5'),
	 ('ZONA 6'),
	 ('ZONA 7'),
	 ('ZONA 8'),
	 ('ZONA 9');


INSERT INTO public."Provincia" (nombre, "idZona") VALUES
('CARCHI', 1),
('ESMERALDAS', 1),
('IMBABURA', 1),
('SUCUMBIOS', 1),
('NAPO', 2),
('ORELLANA', 2),
('PICHINCHA', 2),
('CHIMBORAZO',3),
('COTOPAXI',3),
('PASTAZA',3),
('TUNGURAHUA',3),
('MANABI', 4),
('SANTO DOMINGO DE LOS TSACHILAS', 4),
('BOLIVAR', 5),
('GALAPAGOS', 5),
('GUAYAS', 5),
('LOS RIOS', 5),
('SANTA ELENA', 5),
('AZUAY', 6),
('CAÑAR', 6),
('MORONA SANTIAGO', 6),
('EL ORO', 7),
('LOJA', 7),
('ZAMORA CHINCHIPE', 7),
('DMG', 8),
('DMQ', 9);


INSERT INTO public."Canton" (nombre, "idProvincia") VALUES
('SAN PEDRO DE HUACA', 1),
('TULCAN', 1),
('BOLÍVAR', 1),
('MONTUFAR', 1),
('ESPEJO', 1),
('MIRA', 1),
('ESMERALDAS', 2),
('ELOY ALFARO', 2),
('MUISNE', 2),
('ATACAMES', 2),
('QUININDE', 2),
('SAN LORENZO', 2),
('RIOVERDE', 2),
('IBARRA', 3),
('PIMAMPIRO', 3),
('SAN MIGUEL DE URCUQUI', 3),
('ANTONIO ANTE', 3),
('OTAVALO', 3),
('COTACACHI', 3),
('CASCALES', 4),
('GONZALO PIZARRO', 4),
('SUCUMBIOS', 4),
('LAGO AGRIO', 4),
('CUYABENO', 4),
('PUTUMAYO', 4),
('SHUSHUFINDI', 4),
('ARCHIDONA', 5),
('CARLOS JULIO AROSEMENA TOLA', 5),
('TENA', 5),
('EL CHACO', 5),
('QUIJOS', 5),
('LA JOYA DE LOS SACHAS', 6),
('LORETO', 6),
('ORELLANA', 6),
('AGUARICO', 6),
('CAYAMBE', 7),
('PEDRO MONCAYO', 7),
('MEJIA', 7),
('RUMIÑAHUI', 7),
('PEDRO VICENTE MALDONADO', 7),
('PUERTO QUITO', 7),
('SAN MIGUEL DE LOS BANCOS', 7),
('RIOBAMBA', 8),
('CHAMBO', 8),
('ALAUSI', 8),
('CHUNCHI', 8),
('CUMANDA', 8),
('PALLATANGA', 8),
('COLTA', 8),
('GUAMOTE', 8),
('GUANO', 8),
('PENIPE', 8),
('LATACUNGA', 9),
('LA MANA', 9),
('PANGUA', 9),
('SAQUISILI', 9),
('PUJILI', 9),
('SIGCHOS', 9),
('SALCEDO', 9),
('PASTAZA', 10),
('MERA', 10),
('SANTA CLARA', 10),
('ARAJUNO', 10),
('AMBATO', 11),
('BAÑOS DE AGUA SANTA', 11),
('PATATE', 11),
('SAN PEDRO DE PELILEO', 11),
('SANTIAGO DE PILLARO', 11),
('CEVALLOS', 11),
('MOCHA', 11),
('QUERO', 11),
('TISALEO', 11),
('PORTOVIEJO', 12),
('MANTA', 12),
('MONTECRISTI', 12),
('JARAMIJO', 12),
('JIPIJAPA', 12),
('PUERTO LOPEZ', 12),
('SANTA ANA', 12),
('24 DE MAYO', 12),
('OLMEDO', 12),
('EL CARMEN', 12),
('BOLIVAR', 12),
('JUNIN', 12),
('CHONE', 12),
('FLAVIO ALFARO', 12),
('PICHINCHA', 12),
('PAJAN', 12),
('PEDERNALES', 12),
('JAMA', 12),
('SUCRE', 12),
('SAN VICENTE', 12),
('ROCAFUERTE', 12),
('TOSAGUA', 12),
('SANTO DOMINGO', 13),
('LA CONCORDIA', 13),
('GUARANDA', 14),
('CHILLANES', 14),
('CHIMBO', 14),
('SAN MIGUEL', 14),
('ECHEANDIA', 14),
('CALUMA', 14),
('LAS NAVES', 14),
('ISABELA', 15),
('SAN CRISTOBAL', 15),
('SANTA CRUZ', 15),
('ALFREDO BAQUERIZO MORENO', 16),
('SIMON BOLIVAR', 16),
('BALAO', 16),
('NARANJAL', 16),
('BALZAR', 16),
('COLIMES', 16),
('PALESTINA', 16),
('PEDRO CARBO', 16),
('LOMAS DE SARGENTILLO', 16),
('ISIDRO AYORA', 16),
('EMPALME', 16),
('EL TRIUNFO', 16),
('GNRAL. ANTONIO ELIZALDE', 16),
('MILAGRO', 16),
('NARANJITO', 16),
('CRNEL. MARCELINO MARIDUEÑA', 16),
('DAULE', 16),
('SANTA LUCIA', 16),
('NOBOL', 16),
('SALITRE', 16),
('SAN JACINTO DE YAGUACHI', 16),
('PLAYAS', 16),
('BABAHOYO', 17),
('BABA', 17),
('MONTALVO', 17),
('PUEBLOVIEJO', 17),
('URDANETA', 17),
('QUEVEDO', 17),
('MOCACHE', 17),
('VENTANAS', 17),
('QUINSALOMA', 17),
('VINCES', 17),
('PALENQUE', 17),
('BUENA FE', 17),
('VALENCIA', 17),
('SANTA ELENA', 18),
('LA LIBERTAD', 18),
('SALINAS', 18),
('CUENCA', 19),
('GIRON', 19),
('PUCARA', 19),
('SAN FERNANDO', 19),
('SANTA ISABEL', 19),
('GUALACEO', 19),
('CHORDELEG', 19),
('NABON', 19),
('OÑA', 19),
('PAUTE', 19),
('EL PAN', 19),
('SEVILLA DE ORO', 19),
('GUACHAPALA', 19),
('CAMILO PONCE ENRIQUEZ', 19),
('SIGSIG', 19),
('AZOGUES', 20),
('BIBLIAN', 20),
('DELEG', 20),
('CAÑAR', 20),
('EL TAMBO', 20),
('SUSCAL', 20),
('LA TRONCAL', 20),
('MORONA', 21),
('PALORA', 21),
('HUAMBOYA', 21),
('PABLO SEXTO', 21),
('SUCUA', 21),
('LOGROÑO', 21),
('GUALAQUIZA', 21),
('SAN JUAN BOSCO', 21),
('TAISHA', 21),
('LIMON INDANZA', 21),
('SANTIAGO', 21),
('TIWINTZA', 21),
('CHILLA', 22),
('EL GUABO', 22),
('PASAJE', 22),
('MACHALA', 22),
('ATAHUALPA', 22),
('PORTOVELO', 22),
('ZARUMA', 22),
('BALSAS', 22),
('MARCABELI', 22),
('PIÑAS', 22),
('ARENILLAS', 22),
('HUAQUILLAS', 22),
('LAS LAJAS', 22),
('SANTA ROSA', 22),
('LOJA', 23),
('CATAMAYO', 23),
('CHAGUARPAMBA', 23),
('OLMEDO_LOJA', 23),
('PALTAS', 23),
('CELICA', 23),
('PUYANGO', 23),
('PINDAL', 23),
('ESPINDOLA', 23),
('CALVAS', 23),
('GONZANAMA', 23),
('QUILANGA', 23),
('MACARA', 23),
('SOZORANGA', 23),
('SARAGURO', 23),
('ZAPOTILLO', 23),
('ZAMORA', 24),
('YACUAMBI', 24),
('NANGARITZA', 24),
('CENTINELA DEL CONDOR', 24),
('PAQUISHA', 24),
('CHINCHIPE', 24),
('PALANDA', 24),
('YANTZAZA', 24),
('EL PANGUI', 24),
('GUAYAQUIL', 25),
('SAMBORONDON', 25),
('DURAN', 25),
('QUITO', 26),
('LAS GOLONDRINAS', 3),
('MANGA DEL CURA', 12);


-- Auto-generated SQL script #202211150948
INSERT INTO public."Distrito" (codigo,nombre,"idCanton") VALUES 
('04D01', 'TULCAN', 1),
('04D01','TULCAN',2),
('04D02','MONTUFAR',3),
('04D02', 'MONTUFAR', 4),
('04D03', 'ESPEJO', 5),
('04D03', 'ESPEJO', 6),
('08D01', 'ESMERALDAS', 7),
('08D02', 'ELOY ALFARO-ESMERALDAS', 8),
('08D03', 'ATACAMES', 9),
('08D03', 'ATACAMES', 10),
('08D04', 'QUININDE', 11),
('08D05', 'SAN LORENZO', 12),
('08D06', 'RIO VERDE', 13),
('10D01', 'CIUDAD BLANCA', 14),
('10D01', 'CIUDAD BLANCA', 15),
('10D01', 'CIUDAD BLANCA', 16),
('10D02', 'VALLE DEL AMANECER', 17),
('10D02', 'VALLE DEL AMANECER', 18),
('10D03', 'TIERRA DEL SOL', 19),
('21D01', 'SUCUMBIOS', 20),
('21D01', 'SUCUMBIOS', 21),
('21D01', 'SUCUMBIOS', 22),
('21D02', 'LAGO AGRIO', 23),
('21D03', 'PUTUMAYO', 24),
('21D03', 'PUTUMAYO', 25),
('21D04', 'SHUSHUFINDI', 26),
('15D01', 'TENA', 27),
('15D01', 'TENA', 28),
('15D01', 'TENA', 29),
('15D02', 'EL VALLE DE QUIJOS', 30),
('15D02', 'EL VALLE DE QUIJOS', 31),
('22D01', 'LA JOYA DE LOS SACHAS', 32),
('22D02', 'ORELLANA LORETO', 33),
('22D02', 'ORELLANA LORETO', 34),
('22D03', 'AGUARICO', 35),
('17D10', 'CAYAMBE', 36),
('17D10', 'CAYAMBE', 37),
('17D11', 'RUMIÑAHUI - MEJIA', 38),
('17D11', 'RUMIÑAHUI - MEJIA', 39),
('17D12', 'NOROCCIDENTE', 40),
('17D12', 'NOROCCIDENTE', 41),
('17D12', 'NOROCCIDENTE', 42),
('06D01', 'RIOBAMBA', 43),
('06D01', 'RIOBAMBA', 44),
('06D02', 'ALAUSI', 45),
('06D02', 'ALAUSI', 46),
('06D03', 'PALLATANGA', 47),
('06D03', 'PALLATANGA', 48),
('06D04', 'COLTA', 49),
('06D04', 'COLTA', 50),
('06D05', 'GUANO', 51),
('06D05', 'GUANO', 52),
('05D01', 'LATACUNGA', 53),
('05D02', 'LA MANA', 54),
('05D03', 'PANGUA', 55),
('05D04', 'DANSANTE', 56),
('05D04', 'DANSANTE', 57),
('05D05', 'SIGCHOS', 58),
('05D06', 'SALCEDO', 59),
('16D01', 'PASTAZA', 60),
('16D01', 'PASTAZA', 61),
('16D01', 'PASTAZA', 62),
('16D02', 'ARAJUNO', 63),
('18D01', 'AMBATO NORTE', 64),
('18D02', 'AMBATO SUR', 64),
('18D03', 'BAÑOS', 65),
('18D04', 'PATATE', 66),
('18D04', 'PATATE', 67),
('18D05', 'PILLARO', 68),
('18D06', 'QUERO', 69),
('18D06', 'QUERO', 70),
('18D06', 'QUERO', 71),
('18D06', 'QUERO', 72),
('13D01', 'PORTOVIEJO', 73),
('13D02', 'MANTA', 74),
('13D02', 'MANTA', 75),
('13D02', 'MANTA', 76),
('13D03', 'JIPIJAPA', 77),
('13D03', 'JIPIJAPA', 78),
('13D04', '24 DE MAYO', 79),
('13D04', '24 DE MAYO', 80),
('13D04', '24 DE MAYO', 81),
('13D05', 'EL CARMEN', 82),
('13D06', 'BOLIVAR JUNIN', 83),
('13D06', 'BOLIVAR JUNIN', 84),
('13D07', 'CHONE', 85),
('13D07', 'CHONE', 86),
('13D08', 'PICHINCHA', 87),
('13D09', 'PAJAN', 88),
('13D10', 'PEDERNALES', 89),
('13D10', 'PEDERNALES', 90),
('13D11', 'SUCRE', 91),
('13D11', 'SUCRE', 92),
('13D12', 'ROCAFUERTE', 93),
('13D12', 'ROCAFUERTE', 94),
('23D01', 'SANTO DOMINGO ESTE', 95),
('23D02', 'SANTO DOMINGO OESTE', 95),
('23D03', 'LA CONCORDIA', 96),
('02D01', 'GUARANDA', 97),
('02D02', 'CHILLANES', 98),
('02D03', 'SAN MIGUEL', 99),
('02D03', 'SAN MIGUEL', 100),
('02D04', 'SUBTROPICO', 101),
('02D04', 'SUBTROPICO', 102),
('02D04', 'SUBTROPICO', 103),
('20D01', 'GALAPAGOS', 104),
('20D01', 'GALAPAGOS', 105),
('20D01', 'GALAPAGOS', 106),
('09D11', 'JUJAN SIMON BOLIVAR', 107),
('09D11', 'JUJAN SIMON BOLIVAR', 108),
('09D12', 'NARANJAL BALAO', 109),
('09D12', 'NARANJAL BALAO', 110),
('09D13', 'BALZAR', 111),
('09D13', 'BALZAR', 112),
('09D13', 'BALZAR', 113),
('09D14', 'PEDRO CARBO', 114),
('09D14', 'PEDRO CARBO', 115),
('09D14', 'PEDRO CARBO', 116),
('09D15', 'EMPALME', 117),
('09D16', 'EL TRIUNFO BUCAY', 118),
('09D16', 'EL TRIUNFO BUCAY', 119),
('09D17', 'MILAGRO', 120),
('09D18', 'NARANJITO MARCELINO MARIDUEÑA', 121),
('09D18', 'NARANJITO MARCELINO MARIDUEÑA', 122),
('09D19', 'DAULE', 123),
('09D19', 'DAULE', 124),
('09D19', 'DAULE', 125),
('09D20', 'SALITRE', 126),
('09D21', 'YAGUACHI', 127),
('09D22', 'PLAYAS', 128),
('12D01', 'BABAHOYO', 129),
('12D01', 'BABAHOYO', 130),
('12D01', 'BABAHOYO', 131),
('12D02', 'PUEBLOVIEJO', 132),
('12D02', 'PUEBLOVIEJO', 133),
('12D03', 'QUEVEDO', 134),
('12D03', 'QUEVEDO', 135),
('12D04', 'VENTANAS', 136),
('12D04', 'VENTANAS', 137),
('12D05', 'VINCES', 138),
('12D05', 'VINCES', 139),
('12D06', 'BUENA FE', 140),
('12D06', 'BUENA FE', 141),
('24D01', 'SANTA ELENA', 142),
('24D02', 'LIBERTAD SALINAS', 143),
('24D02', 'LIBERTAD SALINAS', 144),
('01D01', 'CUENCA NORTE', 145),
('01D02', 'CUENCA SUR', 145),
('01D03', 'GIRON', 146),
('01D03', 'GIRON', 147),
('01D03', 'GIRON', 148),
('01D03', 'GIRON', 149),
('01D04', 'GUALACEO', 150),
('01D04', 'GUALACEO', 151),
('01D05', 'NABON', 152),
('01D05', 'NABON', 153),
('01D06', 'PAUTE', 154),
('01D06', 'PAUTE', 155),
('01D06', 'PAUTE', 156),
('01D06', 'PAUTE', 157),
('01D07', 'PONCE ENRIQUEZ', 158),
('01D08', 'SIGSIG', 159),
('03D01', 'AZOGUES', 160),
('03D01', 'AZOGUES', 161),
('03D01', 'AZOGUES', 162),
('03D02', 'CAÑAR', 163),
('03D02', 'CAÑAR', 164),
('03D02', 'CAÑAR', 165),
('03D03', 'LA TRONCAL', 166),
('14D01', 'MORONA', 167),
('14D02', 'SANGAY', 168),
('14D02', 'SANGAY', 169),
('14D02', 'SANGAY', 170),
('14D03', 'CENTRO SUR', 171),
('14D03', 'CENTRO SUR', 172),
('14D04', 'SUR-MORONA', 173),
('14D04', 'SUR-MORONA', 174),
('14D05', 'TAISHA', 175),
('14D06', 'MENDEZ', 176),
('14D06', 'MENDEZ', 177),
('14D06', 'MENDEZ', 178),
('07D01', 'PASAJE', 179),
('07D01', 'PASAJE', 180),
('07D01', 'PASAJE', 181),
('07D02', 'MACHALA', 182),
('07D03', 'ZARUMA', 183),
('07D03', 'ZARUMA', 184),
('07D03', 'ZARUMA', 185),
('07D04', 'PIÑAS', 186),
('07D04', 'PIÑAS', 187),
('07D04', 'PIÑAS', 188),
('07D05', 'HUAQUILLAS', 189),
('07D05', 'HUAQUILLAS', 190),
('07D05', 'HUAQUILLAS', 191),
('07D06', 'SANTA ROSA', 192),
('11D01', 'LOJA', 193),
('11D02', 'CATAMAYO', 194),
('11D02', 'CATAMAYO', 195),
('11D02', 'CATAMAYO', 196),
('11D03', 'CATACOCHA', 197),
('11D04', 'SABANILLA', 198),
('11D04', 'SABANILLA', 199),
('11D04', 'SABANILLA', 200),
('11D05', 'ESPINDOLA', 201),
('11D06', 'CALVAS', 202),
('11D06', 'CALVAS', 203),
('11D06', 'CALVAS', 204),
('11D07', 'MACARA', 205),
('11D07', 'MACARA', 206),
('11D08', 'SARAGURO', 207),
('11D09', 'ZAPOTILLO', 208),
('19D01', 'ZAMORA', 209),
('19D01', 'ZAMORA', 210),
('19D02', 'PAQUISHA', 211),
('19D02', 'PAQUISHA', 212),
('19D02', 'PAQUISHA', 213),
('19D03', 'CHINCHIPE', 214),
('19D03', 'CHINCHIPE', 215),
('19D04', 'YANTZAZA', 216),
('19D04', 'YANTZAZA', 217),
('09D01', 'SUR-DMG', 218),
('09D02', 'ESTEROS', 218),
('09D03', '9 DE OCTUBRE', 218),
('09D04', 'PORTETE', 218),
('09D05', 'MODELO', 218),
('09D06', 'FLORIDA', 218),
('09D07', 'PASCUALES', 218),
('09D08', 'NUEVA PROSPERINA', 218),
('09D09', 'CEIBOS', 218),
('09D10', 'PROGRESO', 218),
('09D23', 'SAMBORONDON', 219),
('09D24', 'DURAN', 220),
('17D01', 'NANEGAL', 221),
('17D02', 'CALDERON', 221),
('17D03', 'LA DELICIA', 221),
('17D04', 'MANUELA SAENZ', 221),
('17D05', 'EUGENIO ESPEJO', 221),
('17D06', 'ELOY ALFARO-DMQ', 221),
('17D07', 'QUITUMBE', 221),
('17D08', 'LOS CHILLOS', 221),
('17D09', 'TUMBACO', 221),
('10D03', 'TIERRA DEL SOL', 222),
('13D05', 'EL CARMEN', 223);

INSERT INTO public."Agente" (nombre) VALUES
('GARCÍA CATAÑA HÉCTOR GONZALO'),
('RIVERA FIERRO ESTEBAN ALEJANDRO'),
('MUÑOZ NAVARRETE RICARDO MARTÍN '),
('FLORES ORTEGA CHRISTIAN ANDRÉS '),
('ARELLANO CATAGNA NELSON ORLANDO'),
('CHAMBA GUAMAN WILSON VLADIMIR'),
('CAMACHO BRICEÑO CHRISTIAN GIOVANNY '),
('CASTILLO ARANDA CLAUDIO DANIEL '),
('FRIAS CONTRERAS WILLIAM MAURICIO '),
('GUACHAMBOSA CANDO CRISTIAN JAVIER'),
('ARMAS INSUASTE JIMENA ELIZABETH'),
('ALDAS JATIVA LUIS FERNANDO'),
('SALAZAR JACOME EDMUNDO ALFREDO'),
('PAREDES RUIZ JOSE PATRICIO'),
('MOLINA VALENZUELA WILIAM CHRISTIAN'),
('AMBAS CONDOR JORGE LUIS'),
('LARA YUNGAN CARLO JAVIER'),
('HARO PINARGOTE GIOVANNY GONZALO'),
('MAJÍN MIÑARCAJA LUIS EDISON '),
('YANEZ CAISALUISA EDISON ROLANDO'),
('TIBANQUIZA CAUJA DEYSI PILAR');

INSERT INTO public."Grado" (nombre) VALUES
('TCNL.'),
('CPTN.'),
('TNTE.'),
('SBTE.'),
('SGOP.'),
('SGOS.'),
('CBOP.'),
('CBOS.'),
('POLI.');

INSERT INTO public."SeccionDelito" (seccion) VALUES
('Delitos contra la integridad personal'),
('Delitos contra el derecho a la propiedad'),
('Delitos contra personas y bienes protegidos por el Derecho Internacional Humanitario'),
('Delitos contra la inviolabilidad de la vida'),
('Delitos contra la seguridad pública'),
('Delitos contra la eficiencia de la administración pública'),
('Delitos contra la integridad sexual y reproductiva'),
('Delitos contra la seguridad de los activos de los sistemas de información y comunicación'),
('Delitos por la producción o tráfico ilícito de sustancias catalogadas sujetas a fiscalización'),
('Delitos contra los recursos mineros'),
('Acto Administrativo'),
('Delito de odio'),
('Contravención de actos ilegales tendientes al alza de precios de productos sujetos a precio oficial'),
('Delitos contra la tutela judicial efectiva'),
('Diversas formas de explotación'),
('Delitos contra la actividad hidrocarburífera, derivados de hidrocarburos, gas licuado de petróleo y biocombustibles'),
('Delitos económicos'),
('Delitos contra la humanidad'),
('Contravención contra la seguridad pública'),
('Apremio'),
('Terrorismo y su financiación'),
('Delito contra el derecho al honor y buen nombre'),
('Delitos contra el sistema financiero'),
('Delitos contra los derechos de los consumidores, usuarios y otros agentes del mercado'),
('Delitos contra el derecho a la salud'),
('Delitos contra los recursos naturales'),
('Delitos contra la administración aduanera'),
('Contravenciones contra el derecho de propiedad'),
('Contravenciones'),
('Delitos culposos de tránsito'),
('Delitos contra el régimen dedesarrollo'),
('Delitos contra la biodiversidad'),
('Delitos contra el derecho a la cultura'),
('Delitos contra el derecho a la intimidad personal y familiar'),
('Delitos contra el derecho a la igualdad'),
('Delitos contra la fe pública'),
('Delitos contra la gestión ambiental'),
('Delitos contra del régimen monetario'),
('Delitos contra los derechos de participación'),
('Contravención contra el derecho al trabajo'),
('Delitos contra el derecho al trabajo y la Seguridad Social'),
('Contravención de maltrato y muerte de mascotas o animales de compañía'),
('Contravenciones contra la eficiencia de la administración pública'),
('Contravenciones contra la tutela judicial efectiva'),
('Delitos contra la libertad personal'),
('Delitos contra la libertad de expresión y de culto'),
('Delitos contra el derecho a la identidad'),
('Tentativa'),
('Delitos contra la migración'),
('Trata de Personas'),
('Contravención de violencia contra la mujer o miembros del núcleo familiar'),
('Delitos de violencia contra la mujer o miembros del núcleo familiar');

INSERT INTO public."Delito" (delito,"idSeccion") VALUES 
('Abandono de persona', 1),
('Intimidación', 1),
('Lesiones', 1),
('Tortura', 1),
('Abigeato', 2),
('Abuso de confianza', 2),
('Apropiación fraudulenta por medios electrónicos', 2),
('Aprovechamiento ilícito de servicios públicos', 2),
('Comercialización de bienes de uso policial o militar hurtados o robados', 2),
('Comercialización ilícita de terminales móviles', 2),
('Daño a bien ajeno', 2),
('Estafa', 2),
('Extorsión', 2),
('Falsificación de marcas y piratería lesiva contra los derechos de autor', 2),
('Hurto', 2),
('Hurto a domicilio', 2),
('Hurto a embarcaciones de espacios acuáticos', 2),
('Hurto a entidades financieras', 2),
('Hurto a entidades públicas', 2),
('Hurto a establecimientos de colectivos u organizaciones sociales', 2),
('Hurto a instituciones de salud', 2),
('Hurto a instituciones educativas', 2),
('Hurto a personas', 2),
('Hurto a unidades económicas', 2),
('Hurto a vehículos de transporte de valores', 2),
('Hurto de bienes accesorios y autopartes de vehículos', 2),
('Hurto de bienes de uso policial o militar', 2),
('Hurto de bienes patrimoniales', 2),
('Hurto de lo requisado', 2),
('Hurto de motocicletas', 2),
('Hurto de vehículos', 2),
('Hurto en ejes viales o carreteras', 2),
('Infraestructura ilícita', 2),
('Insolvencia fraudulenta', 2),
('Intercambio, comercialización o compra de información de equipos terminales móviles', 2),
('Ocupación, uso ilegal de suelo o tráfico de tierras', 2),
('Otros robos', 2),
('Quiebra', 2),
('Quiebra fraudulenta de persona jurídica', 2),
('Receptación', 2),
('Reemplazo de identificación de terminales móviles', 2),
('Reprogramación o modificación de información de equipos terminales móviles', 2),
('Robo a domicilio', 2),
('Robo a embarcaciones de espacios acuáticos', 2),
('Robo a entidades financieras', 2),
('Robo a establecimientos de colectivos u organizaciones sociales', 2),
('Robo a institución pública', 2),
('Robo a instituciones de salud', 2),
('Robo a instituciones educativas', 2),
('Robo a personas', 2),
('Robo a unidades económicas', 2),
('Robo a vehículos de transporte de valores', 2),
('Robo de bienes accesorios y autopartes de vehículos', 2),
('Robo de bienes patrimoniales', 2),
('Robo de motocicletas', 2),
('Robo de vehículos', 2),
('Robo en ejes viales o carreteras', 2),
('Usurpación', 2),
('Abolición y suspensión de derechos de persona protegida', 3),
('Abuso de emblemas', 3),
('Aplicación de disposiciones en conflicto armado internacional o no internacional', 3),
('Armas prohibidas por el Derecho Internacional Humanitario', 3),
('Ataque a bienes protegidos', 3),
('Ataque a persona protegida con fines terroristas', 3),
('Atentado a la integridad sexual y reproductiva de persona protegida', 3),
('Bienes protegidos por el Derecho Internacional Humanitario', 3),
('Castigos colectivos en persona protegida', 3),
('Contribuciones arbitrarias', 3),
('Denegación de garantías judiciales de persona protegida', 3),
('Destrucción o apropiación de bienes de la parte adversa', 3),
('Empleo de métodos prohibidos en la conducción de conflicto armado', 3),
('Homicidio de persona protegida', 3),
('Infracciones contra los participantes activos en conflicto armado', 3),
('Lesión a la integridad física de persona protegida', 3),
('Modificación ambiental con fines militares', 3),
('Mutilaciones o experimentos en persona protegida', 3),
('Obstaculización de tareas sanitarias y humanitarias', 3),
('Omisión de medidas de protección', 3),
('Omisión de medidas de socorro y asistencia humanitaria', 3),
('Personas protegidas por el Derecho Internacional Humanitario', 3),
('Privación de libertad de persona protegida', 3),
('Prolongación de hostilidades', 3),
('Reclutamiento de niños, niñas y adolescentes', 3),
('Toma de rehenes', 3),
('Tortura y tratos crueles, inhumanos o degradantes en persona protegida', 3),
('Traslado arbitrarioo ilegal', 3),
('Utilización de armas prohibidas', 3),
('Aborto con muerte', 4),
('Aborto consentido', 4),
('Aborto no consentido', 4),
('Aborto no punible', 4),
('Asesinato', 4),
('Femicidio', 4),
('Homicidio', 4),
('Homicidio culposo', 4),
('Homicidio culposo por mala práctica profesional', 4),
('Sicariato', 4),
('Abstención de la ejecución de operaciones en conmoción interna', 5),
('Abuso de arma de fuego', 5),
('Actos hostiles contra el Estado', 5),
('Armas de fuego, municiones y explosivos no autorizados', 5),
('Atentado contra la seguridad de las operaciones militares o policiales', 5),
('Deserción', 5),
('Destrucción de registros', 5),
('Destrucción o inutilización de bienes', 5),
('Espionaje', 5),
('Grupos subversivos', 5),
('Incendio', 5),
('Incitación a discordia entre ciudadanos', 5),
('Infiltración en zonas de seguridad', 5),
('Instigación', 5),
('Instrucción militar ilegal', 5),
('Insubordinación', 5),
('Ocultamiento de objetos para el socorro', 5),
('Omisión de aviso de deserción', 5),
('Omisión en el abastecimiento', 5),
('Paralización de un servicio público', 5),
('Quebrantamiento de tregua o armisticio', 5),
('Rebelión', 5),
('Sabotaje', 5),
('Sedición', 5),
('Tenencia y porte de armas', 5),
('Tentativa de asesinato contra la o el Presidente de la República', 5),
('Tráfico ilícito de armas de fuego, armas químicas, nucleares o biológicas', 5),
('Traición a la Patria', 5),
('Usurpación y retención ilegal de mando', 5),
('Abuso de facultades', 6),
('Alteración de evidencias y elementos de prueba', 6),
('Ataque o resistencia', 6),
('Cohecho', 6),
('Concusión', 6),
('Delitos contra los bienes institucionales de Fuerzas Armadas o Policía Nacional', 6),
('Elusión de responsabilidades de las o los servidores de las Fuerzas Armadas o Policía Nacional', 6),
('Enriquecimiento ilícito', 6),
('Extralimitación en la ejecución de un acto de servicio', 6),
('Incumplimiento de decisiones legítimas de autoridad competente', 6),
('Oferta de realizar tráfico de influencias', 6),
('Peculado', 6),
('Ruptura de sellos', 6),
('Testaferrismo', 6),
('Tráfico de influencias', 6),
('Uso de fuerza pública contra órdenes de autoridad', 6),
('Usurpación y simulación de funciones públicas', 6),
('Abuso sexual', 7),
('Acoso sexual', 7),
('Contacto con finalidad sexual con menores de dieciocho años por medios electrónicos', 7),
('Corrupción de niñas, niños y adolescentes', 7),
('Distribución de material pornográfico a niñas, niños y adolescentes', 7),
('Estupro', 7),
('Inseminación no consentida', 7),
('Oferta de servicios sexuales con menores de dieciocho años por medios electrónicos', 7),
('Privación forzada de capacidad de reproducción', 7),
('Utilización de personas para exhibición pública con fines de naturaleza sexual', 7),
('Violación', 7),
('Acceso no consentido a un sistema informático, telemático o de telecomunicaciones', 8),
('Ataque a la integridad de sistemas informáticos', 8),
('Delitos contra la información pública reservada legalmente', 8),
('Interceptación ilegal de datos', 8),
('Revelación ilegal de base de datos', 8),
('Transferencia electrónica de activo patrimonial', 8),
('Acciones de mala fe para involucrar en delitos', 9),
('Cantidad admisible para uso o consumo personal', 9),
('Destrucción de objetos materiales', 9),
('Organización o financiamiento para la producción o tráfico ilícitos de sustancias catalogadas sujetas a fiscalización', 9),
('Prescripción injustificada', 9),
('Producción ilícita de sustancias catalogadas sujetas a fiscalización', 9),
('Siembra o cultivo', 9),
('Suministro de sustancias estupefacientes, psicotrópicas o preparados que las contengan', 9),
('Sustancias catalogadas sujetas a fiscalización', 9),
('Tráfico ilícito de sustancias catalogadas sujetas a fiscalización', 9),
('Actividad ilícita de recursos mineros', 10),
('Financiamiento o suministro de maquinarias para extracción ilícita de recursos mineros', 10),
('Acto Administrativo', 11),
('Actos de odio', 12),
('Actos ilegales tendientes al alza de precios de productos sujetos a precio oficial', 13),
('Acusación o denuncia maliciosa', 14),
('Evasión', 14),
('Fraude procesal', 14),
('Ingreso de artículos prohibidos', 14),
('Omisión de denuncia por parte de un profesional de la salud', 14),
('Perjurio y falso testimonio', 14),
('Prevaricato de las o los abogados', 14),
('Prevaricato de las o los jueces o árbitros', 14),
('Revelación de identidad de agente encubierto, informante, testigo o persona protegida', 14),
('Adopción ilegal', 15),
('Comercialización de pornografía con utilización de niñas, niños o adolescentes', 15),
('Empleo de personas para mendicidad', 15),
('Explotación sexual de personas', 15),
('Extracción y tratamiento ilegal de órganos y tejidos', 15),
('Pornografía con utilización de niñas, niños o adolescentes', 15),
('Promesa de matrimonio o unión de hecho servil', 15),
('Prostitución forzada', 15),
('Publicidad de tráfico de órganos', 15),
('Realización de procedimientos de trasplante sin autorización', 15),
('Trabajos forzados u otras formas de explotación laboral', 15),
('Tráfico de órganos', 15),
('Turismo para la extracción, tratamiento ilegal o comercio de órganos', 15),
('Turismo sexual', 15),
('Adulteración de la calidad o cantidad de productos derivados de hidrocarburos, gas licuado de petróleo o biocombustibles', 16),
('Almacenamiento, transporte, envasado, comercialización o distribución ilegal de hidrocarburos en las provincias fronterizas, puertos marítimos o fluviales o mar territorial', 16),
('Almacenamiento, transporte, envasado, comercialización o distribución ilegal o mal uso de productos derivados de hidrocarburos, gas licuado de petróleo o biocombustibles', 16),
('Paralización del servicio de distribución de combustibles', 16),
('Sustracción de hidrocarburos', 16),
('Agiotaje', 17),
('Autorización indebida de contrato de seguro', 17),
('Defraudaciones bursátiles', 17),
('Divulgación de información financiera reservada', 17),
('Falsedad de información', 17),
('Falsedad documental en el mercado de valores', 17),
('Incriminación falsa por lavado de activos', 17),
('Lavado de activos', 17),
('Ocultamiento de información', 17),
('Omisión de control de lavado de activos', 17),
('Operaciones indebidas de seguros', 17),
('Pánico económico', 17),
('Simulación de exportaciones o importaciones', 17),
('Usura', 17),
('Agresión', 18),
('Apartheid', 18),
('Delitos de lesa humanidad', 18),
('Deportación o traslado forzoso de población', 18),
('Desaparición forzada', 18),
('Desaparición involuntaria de personas', 18),
('Ejecución extrajudicial', 18),
('Esclavitud', 18),
('Etnocidio', 18),
('Exterminio', 18),
('Genocidio', 18),
('Persecución', 18),
('Apología', 19),
('Apremio', 20),
('Asociación Ilícita', 21),
('Delincuencia Organizada', 21),
('Falsa incriminación', 21),
('Financiación del terrorismo', 21),
('Terrorismo', 21),
('Calumnia', 22),
('Captación ilegal de dinero', 23),
('Descuento indebido de valores', 23),
('Falsedad de información financiera', 23),
('Pánico financiero', 23),
('Casinos, salas de juego, casas de apuestas o negocios dedicados a la realización de juegos de azar', 24),
('Engaño al comprador respecto a la identidad o calidad de las cosas o servicios vendidos', 24),
('Contaminación de sustancias destinadas al consumo humano', 25),
('Daño permanente a la salud', 25),
('Desatención del servicio de salud', 25),
('Manipulación genética', 25),
('Producción, fabricación, comercialización y distribución de medicamentos e insumos caducados', 25),
('Contaminación del aire', 26),
('Delitos contra el agua', 26),
('Delitos contra suelo', 26),
('Contrabando', 27),
('Defraudación aduanera', 27),
('Mal uso de exenciones o suspensiones tributarias aduaneras', 27),
('Receptación aduanera', 27),
('Contravención de abigeato', 28),
('Contravención de hurto', 28),
('Contravenciones de cuarta clase', 29),
('Contravenciones de primera clase', 29),
('Contravenciones de segunda clase', 29),
('Contravenciones de tercera clase', 29),
('Contravenciones en escenarios deportivos y de concurrencia masiva', 29),
('Daños materiales', 30),
('Daños mecánicos previsibles en transporte público', 30),
('Exceso de pasajeros en transporte público', 30),
('Lesiones causadas por accidente de tránsito', 30),
('Muerte causada por conductor en estado de embriaguez o bajo los efectos de sustancias estupefacientes, psicotrópicas o preparados que las contengan', 30),
('Muerte culposa', 30),
('Muerte provocada por negligencia de contratista o ejecutor de obra', 30),
('Defraudación tributaria', 31),
('Enriquecimiento privado no justificado', 31),
('Delitos contra la flora y fauna silvestres', 32),
('Delitos contra los recursos del patrimonio genético nacional', 32),
('Incendios forestales y de vegetación', 32),
('Invasión de áreas de importancia ecológica', 32),
('Destrucción de bienes del patrimonio cultural', 33),
('Falsificación o adulteración de bienes del patrimonio cultural', 33),
('Sustracción de bienes del patrimonio cultural', 33),
('Transporte y comercialización ilícitos y tráfico de bienes del patrimonio cultural', 33),
('Difusión de información de circulación restringida', 34),
('Revelación de secreto', 34),
('Violación a la intimidad', 34),
('Violación de propiedad privada', 34),
('Discriminación', 35),
('Ejercicio ilegal de la profesión', 36),
('Falsificación de firmas', 36),
('Falsificación y uso de documento falso', 36),
('Falsificación, forjamiento o alteración de recetas', 36),
('Falsedad u ocultamiento de información ambiental', 37),
('Gestión prohibida o no autorizada de productos, residuos, desechos o sustancias peligrosas', 37),
('Falsificación de moneda y otros documentos', 38),
('Producción, tenencia y tráfico de instrumentos destinados a la falsificación de moneda', 38),
('Tráfico de moneda', 38),
('Falso sufragio', 39),
('Fraude electoral', 39),
('Obstaculización de proceso electoral', 39),
('Sustracción de papeletas electorales', 39),
('Falta de afiliación al Instituto Ecuatoriano de Seguridad Social', 40),
('Falta de afiliación al Instituto Ecuatoriano de Seguridad Social por parte de una persona jurídica', 41),
('Impedimento o limitación del derecho a huelga', 41),
('Retención ilegal de aportación a la seguridad social', 41),
('Maltrato o muerte de mascotas o animales de compañía', 42),
('Peleas o combates entre perros', 42),
('Negativa a prestar auxilio solicitado por autoridad civil', 43),
('Usurpación de uniformes e insignias', 43),
('Omisión de denuncia', 44),
('Privación ilegal de libertad', 45),
('Secuestro', 45),
('Secuestro extorsivo', 45),
('Simulación de secuestro', 45),
('Restricción a la libertad de culto', 46),
('Restricción a la libertad de expresión', 46),
('Suplantación de identidad', 47),
('Supresión, alteración o suposición de la identidad y estado civil', 47),
('Tentativa de robo', 48),
('Tentativa de secuestro', 48),
('Tentativa de violación', 48),
('Tentativa homicidio/asesinato', 48),
('Tráfico ilícito de migrantes', 49),
('Trata de personas', 50),
('Violencia contra la mujer o miembros del núcleo familiar', 51),
('Violencia física contra la mujer o miembros del núcleo familiar', 52),
('Violencia psicológica contra la mujer o miembros del núcleo familiar', 52),
('Violencia sexual contra la mujer o miembros del núcleo familiar', 52);

INSERT INTO public."ModalidadDelito" (modalidad) VALUES 
('Abuso de autoridad'),
('Adquirir cupos'),
('Agresión sexual'),
('Ajuste de cuentas'),
('Argucias legales'),
('Arranchadores'),
('Asalto en cajeros automáticos'),
('Asalto por obstrucción en la vía'),
('Asalto/atraco'),
('Aturdimiento por sustancias'),
('Bujiazo'),
('Cajueleros'),
('Carteristas'),
('Chulqueros'),
('Clonación de tarjetas'),
('Cordelero'),
('Coyoterismo'),
('Cuentero'),
('Descuideros/distracción'),
('Enfrentamiento'),
('Engaño'),
('Escalamiento'),
('Estriles'),
('Estruche'),
('Evitar sanciones'),
('Extorsivo'),
('Fallos favorables'),
('Falsas empleadas domesticas'),
('Falsificación'),
('Falsificación de marcas'),
('Falso pasajero'),
('Falso personaje'),
('Falso profesional'),
('Falsos arrendatarios'),
('Falsos artesanos'),
('Falsos funcionarios públicos'),
('Firma ajena'),
('Falderos'),
('Foramen'),
('Incumplimiento de acuerdos de palabra'),
('Infanticidio'),
('Inhibidores'),
('Intimidación'),
('Lanzas'),
('Linchamiento'),
('Llamada o mensaje millonario'),
('Loteriazo'),
('Maltrato infantil'),
('Manejo fraudulento'),
('Paqueteros'),
('Para evitar acción administrativa'),
('Para evitar acción judicial'),
('Paveadores'),
('Phishing'),
('Por revelación a la privacidad'),
('Préstamo por internet'),
('Prestar servicios'),
('Problemas pasionales'),
('Religioso'),
('Riña'),
('Sacapintas'),
('Seducción'),
('Skimming'),
('Tramitadores'),
('Uso de bebidas alcohólicas'),
('Uso o pago con tarjetas robadas'),
('Uso tarjeta magnética'),
('Venganza'),
('Ventas por internet'),
('Violación de sistemas electrónicos e información'),
('Wash and wash');

INSERT INTO public."Condicion" (condicion) VALUES 
('ADUANERO'),
('AGENTE DE TRANSITO'),
('EMBARAZADA'),
('EMPLEADO PRIVADO'),
('FUNCIONARIO PUBLICO'),
('GUIA PENITENCIARIO'),
('REFUGIADO'),
('MILITAR ACTIVO'),
('MILITAR PASIVO'),
('POLICIA ACTIVO'),
('POLICIA PASIVO'),
('NINGUNO');

INSERT INTO public."Parentesco" (nombre) VALUES 
('PADRES'),
('HERMANOS'),
('PRIMOS'),
('TIOS'),
('OTROS FAMILIARES'),
('PROFESOR'),
('COMPAÑERO DE TRABAJO'),
('COMPAÑERO DE ESTUDIO'),
('VECINO DEL LUGAR DONDE HABITA'),
('DESCONOCIDO'),
('PADRASTROS'),
('MADRASTRA'),
('ABUELOS');